apiVersion: v1
kind: Service
metadata:
  name: {{ include "azt-nginx.fullname" . }}
  labels:
    {{- include "azt-nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http-nginx
  selector:
    {{- include "azt-nginx.selectorLabels" . | nindent 4 }}
